---
- name: Install python-yaml
  apt: name=python-yaml state=latest

- name: Install docker python client
  pip: name=docker-py state=latest version="{{ docker_dockerpy_version }}"

- name: Install docker-compose
  get_url:
    url: "{{ dockercompose_url }}"
    dest: "{{ dockercompose_install_dir }}"
    mode: a+x
