---
- name: Install python-yaml
  apt: name=python-yaml state=latest

- name: Install docker and docker-compose python clients
  pip:
    name: docker-py=={{ docker_py_version }} docker-compose=={{ dockercompose_py_version }}
    state: present

- name: Install docker-compose
  get_url:
    url: "{{ dockercompose_url }}"
    dest: "{{ dockercompose_install_dir }}"
    mode: a+x
